Added kustomize directory

diff --git a/.github/workflows/e2ecicd.yaml b/.github/workflows/e2ecicd.yaml
--- a/.github/workflows/e2ecicd.yaml
+++ b/.github/workflows/e2ecicd.yaml
@@ -172,12 +172,16 @@ jobs:
     runs-on: ubuntu-latest
 
     env:
+      TF_IN_AUTOMATION: "1"
       S3_BUCKET: ${{ secrets.S3_BUCKET }}
       S3_REGION: ${{ secrets.S3_REGION }}
       DYNAMODB_TABLE: ${{ secrets.DYNAMODB_TABLE }}
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
+      ENVIRONMENT: ${{ needs.build.outputs.currentENV }}
+      TF_VAR_environment: ${{ needs.build.outputs.currentENV }}
+
     steps:
     - name: Checkout Code
       uses: actions/checkout@v3
@@ -188,8 +192,6 @@ jobs:
     - name: Terraform Init
       run: |
         cd terraform
-        export ENVIRONMENT=${{ needs.build.outputs.currentENV }}
-        export TF_VAR_environment=$ENVIRONMENT
         terraform init \
           -backend-config="bucket=${S3_BUCKET}" \
           -backend-config="key=state/${ENVIRONMENT}-env.tfstate" \
@@ -199,14 +201,12 @@ jobs:
 
     - name: Terraform Plan
       id: tf-plan
-      run: "cd terraform\nexport ENVIRONMENT=${{ needs.build.outputs.currentENV }}\nexport TF_VAR_environment=$ENVIRONMENT\nexport exitcode=0\nterraform plan -detailed-exitcode -no-color -out tfplan\nexport exitcode=$?\nif [ $exitcode -eq 1 ]; then\n  echo \"Terraform Plan Failed!\"\n  exit 1\nelif [ $exitcode -eq 2 ]; then\n   echo \"Drift detected. Need to run terraform apply\"\n   echo \"exitcode=$exitcode\" >> $GITHUB_OUTPUT\n   exit 0\nelse \n  exit 0\nfi\n      #magic___^_^___line\n"
+      run: "cd terraform\nexport exitcode=0\nterraform plan -detailed-exitcode -no-color -out tfplan\nexport exitcode=$?\nif [ $exitcode -eq 1 ]; then\n  echo \"Terraform Plan Failed!\"\n  exit 1\nelif [ $exitcode -eq 2 ]; then\n   echo \"Drift detected. Need to run terraform apply\"\n   echo \"exitcode=$exitcode\" >> $GITHUB_OUTPUT\n   exit 0\nelse \n  exit 0\nfi\n      #magic___^_^___line\n"
 
 
     - name: Terraform Apply
       run: |
         cd terraform
-        export ENVIRONMENT=${{ needs.build.outputs.currentENV }}
-        export TF_VAR_environment=$ENVIRONMENT
         terraform apply -auto-approve tfplan
       if: ${{ steps.tf-plan.outputs.exitcode == '2' }}
 
@@ -223,17 +223,11 @@ jobs:
         sudo ./aws/install --update
 
     - name: Configure Kubectl
-      run: |
-        export ENVIRONMENT=${{ needs.build.outputs.currentENV }}
-        export TF_VAR_environment=$ENVIRONMENT
-        aws eks --region ${{ secrets.S3_REGION }} update-kubeconfig \
-        --name e2ecicd-eks-${ENVIRONMENT}
+      run: aws eks --region ${{ secrets.S3_REGION }} update-kubeconfig \ --name e2ecicd-eks-${ENVIRONMENT}
 
     - name: Check Ingress Contoller
       id: check-ingress
-      run: |
-        kubectl -n ingress-nginx get pods || echo "install=false" >> "$GITHUB_OUTPUT" \
-        && echo "install=true" >> "$GITHUB_OUTPUT"
+      run: kubectl -n ingress-nginx get pods || echo "install=false" >> "$GITHUB_OUTPUT" \ && echo "install=true" >> "$GITHUB_OUTPUT"
 
     - name: Install Helm
       run: |
@@ -263,20 +257,16 @@ jobs:
 
     - name: Create Namespace
       run: |
-        export ENVIRONMENT=${{ needs.build.outputs.currentENV }}
         NAMESPACE=app-${ENVIRONMENT}
         kubectl get ns ${NAMESPACE} || kubectl create namespace ${NAMESPACE}
 
     - name: Update Image
       run: |
-        export ENVIRONMENT=${{ needs.build.outputs.currentENV }}
         image=${{ secrets.DOCKER_USERNAME }}/node-app:${{ needs.build.outputs.currentVersion }}-${ENVIRONMENT}
         sed -i "s|image: .*$|image: ${image}|" kustomize/overlays/${ENVIRONMENT}/deploy-${ENVIRONMENT}.yaml
 
     - name: Install Kustomized Manifests
-      run: |
-        export ENVIRONMENT=${{ needs.build.outputs.currentENV }}
-        kubectl apply -k kustomize/overlays/${ENVIRONMENT}
+      run: kubectl apply -k kustomize/overlays/${ENVIRONMENT}
 
     - name: Rollout Restart Deployment
       run: kubectl -n app-${{ needs.build.outputs.currentENV }} rollout restart deployment web-deployment
