Fix image name for staging

diff --git a/.github/workflows/e2ecicd.yaml b/.github/workflows/e2ecicd.yaml
--- a/.github/workflows/e2ecicd.yaml
+++ b/.github/workflows/e2ecicd.yaml
@@ -121,8 +121,8 @@ jobs:
 
     - name: Docker Build and Push Staging
       run: |
-        docker build -t ${{ secrets.DOCKER_USERNAME }}/node-app:${{ steps.updated-version.outputs.version }}-stag .
-        docker push ${{ secrets.DOCKER_USERNAME }}/node-app:${{ steps.updated-version.outputs.version }}-stag
+        docker build -t ${{ secrets.DOCKER_USERNAME }}/node-app:${{ steps.updated-version.outputs.version }}-staging .
+        docker push ${{ secrets.DOCKER_USERNAME }}/node-app:${{ steps.updated-version.outputs.version }}-staging
       if: github.ref == 'refs/heads/staging'
 
     - name: Docker Build and Push Prod
@@ -201,8 +201,23 @@ jobs:
 
     - name: Terraform Plan
       id: tf-plan
-      run: "cd terraform\nexport exitcode=0\nterraform plan -detailed-exitcode -no-color -out tfplan\nexport exitcode=$?\nif [ $exitcode -eq 1 ]; then\n  echo \"Terraform Plan Failed!\"\n  exit 1\nelif [ $exitcode -eq 2 ]; then\n   echo \"Drift detected. Need to run terraform apply\"\n   echo \"exitcode=$exitcode\" >> $GITHUB_OUTPUT\n   exit 0\nelse \n  exit 0\nfi\n      #magic___^_^___line\n"
+      run: |
+        cd terraform
+        export exitcode=0
+        terraform plan -detailed-exitcode -no-color -out tfplan
+        export exitcode=$?
 
+             
+        if [ $exitcode -eq 1 ]; then
+          echo "Terraform Plan Failed!"
+          exit 1
+        elif [ $exitcode -eq 2 ]; then
+           echo "Drift detected. Need to run terraform apply"
+           echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+           exit 0
+        else 
+          exit 0
+        fi
 
     - name: Terraform Apply
       run: |
