modified worflow: Added check at TF plan stage

diff --git a/.github/workflows/e2ecicd.yaml b/.github/workflows/e2ecicd.yaml
--- a/.github/workflows/e2ecicd.yaml
+++ b/.github/workflows/e2ecicd.yaml
@@ -199,13 +199,17 @@ jobs:
           export ENVIRONMENT=$(echo "${{ github.ref }}" | sed -e "s/refs\/heads\///g")
           export TF_VAR_environment=$ENVIRONMENT
           export exitcode=0
-          terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
+          terraform plan -detailed-exitcode -no-color -out tfplan
+          export exitcode=$?
 
           echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
         
           if [ $exitcode -eq 1 ]; then
-            echo Terraform Plan Failed!
+            echo "Terraform Plan Failed!"
             exit 1
+          elseif [ $exitcode -eq 2 ]; then
+             echo "Infra matches config. Nothing to change"
+             exit 0
           else 
             exit 0
           fi
